[NoLockpickActivate]
; Set to 4 to see the outputs from AOB scans
; Set to 5 for trace logging of every time the entry point hits
LogLevel = 3

; Activate when using a key?
[ActivateWithKey]
CONT = false
DOOR = true

; Activate when using a lockpick?
[ActivateWithLockpick]
CONT = false
DOOR = true